# Generated by Django 5.2.5 on 2025-09-04 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=100)),
                ('art_category', models.CharField(max_length=60)),
                ('artist_name', models.CharField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.model', verbose_name='username'))),
                ('description', models.CharField()),
                ('art_image', models.ImageField(upload_to='D:\\hack2skill\\Artist_Assistant\x07rtists\\media')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=500)),
                ('art_category', models.CharField(max_length=60)),
                ('Story', models.CharField()),
                ('profile', models.ImageField(upload_to='D:\\hack2skill\\Artist_Assistant\x07rtists\\media')),
            ],
        ),
    ]
