# Generated by Django 5.2.5 on 2025-09-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_artist_id_alter_artist_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.AddField(
            model_name='artist',
            name='about',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Story',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.ImageField(null=True, upload_to='D:\\hack2skill\\Artist_Assistant\x07rtists\\media'),
        ),
    ]
