# Generated by Django 5.2.5 on 2025-09-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_remove_artist_bio_artist_about_alter_artist_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_image',
            field=models.ImageField(upload_to='artists/media'),
        ),
        migrations.AlterField(
            model_name='art',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist', verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Story',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='artists/media'),
        ),
    ]
