# Generated by Django 5.2.5 on 2025-09-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_art_art_image_alter_art_artist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='story_video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='art',
            name='art_image',
            field=models.ImageField(upload_to='artists'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='artists'),
        ),
    ]
