# Generated by Django 5.2.5 on 2025-09-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_story_video_alter_art_art_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='Story',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='story_video',
        ),
        migrations.AddField(
            model_name='artist',
            name='video_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='story',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
