# Generated by Django 5.2.5 on 2025-09-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_remove_artist_story_remove_artist_story_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='video_url',
        ),
        migrations.AddField(
            model_name='artist',
            name='story_video',
            field=models.FileField(blank=True, null=True, upload_to='story_videos/'),
        ),
    ]
